"""Generate the endpoint security matrix from FastAPI dependency metadata."""

import os
from pathlib import Path

os.environ.setdefault("DATABASE_URL", "postgresql+asyncpg://matrix:matrix@localhost/matrix")
os.environ.setdefault("DATABASE_SYNC_URL", "postgresql+psycopg://matrix:matrix@localhost/matrix")

from fastapi.routing import APIRoute, iter_route_contexts

from app.main import app

PUBLIC = {"/api/health", "/api/health/database", "/api/health/live", "/api/health/ready", "/api/health/version"}
AUTH_ONLY_PREFIXES = ("/api/auth/",)
INTERNAL = {"/internal/metrics": "metrics-token"}
FRONTEND = {
    "/": "dashboard:read",
    "/assistant": "assistant:use",
    "/analytics": "analytics:read",
    "/decisions": "decisions:request",
    "/bins": "analytics:read",
    "/trucks": "analytics:read",
    "/workforce": "analytics:read",
    "/documents": "documents:read",
    "/ingestion": "datasets:read or documents:ingest",
    "/system/evaluations": "evaluations:read",
    "/system/prompts": "prompts:read",
    "/system/traces": "traces:read",
    "/auth/signin": "public",
    "/auth/signout": "authenticated",
    "/auth/error": "public",
}


def permissions(route) -> set[str]:
    output: set[str] = set()

    def visit(dependant) -> None:
        call = dependant.call
        output.update(getattr(call, "required_permissions", ()))
        for child in dependant.dependencies:
            visit(child)

    visit(route.dependant)
    return output


def category(path: str) -> str:
    if any(value in path for value in ("evaluation", "ingestion", "documents/ingest", "chat/")):
        return "expensive"
    if any(value in path for value in ("prompts", "audit")):
        return "admin"
    return "default"


def rows() -> list[tuple[str, str, str, str, str, str, str]]:
    result = []
    for route in iter_route_contexts(app.routes):
        if not isinstance(route.original_route, APIRoute) or not route.path or not (route.path.startswith("/api/") or route.path.startswith("/internal/")):
            continue
        route_permissions = permissions(route)
        is_public = route.path in PUBLIC
        internal_permission = INTERNAL.get(route.path)
        if not is_public and not route_permissions and not route.path.startswith(AUTH_ONLY_PREFIXES) and not internal_permission:
            raise RuntimeError(f"Protected route lacks permission declaration: {route.path}")
        for method in sorted((route.methods or set()) - {"HEAD", "OPTIONS"}):
            event = "http.mutation" if method in {"POST", "PUT", "PATCH", "DELETE"} else ("authorization.denial" if route_permissions else "none")
            production = "no" if "debug" in route.path or route.path.startswith("/api/retrieval") else "yes"
            result.append(
                (
                    route.path,
                    method,
                    "no" if is_public else "yes",
                    ", ".join(sorted(route_permissions)) or internal_permission or "authenticated",
                    category(route.path),
                    event,
                    production,
                )
            )
    for path, permission in FRONTEND.items():
        result.append((path, "GET", "no" if permission == "public" else "yes", permission, "proxy", "none", "yes"))
    result.append(
        ("/api/backend/{allow-listed-path}", "GET/POST/PUT/PATCH/DELETE", "yes", "delegated to backend", "backend category", "backend mutation", "yes")
    )
    return sorted(result)


def main() -> None:
    lines = [
        "# Endpoint security matrix",
        "",
        "Generated by `scripts/generate_endpoint_matrix.py`; do not edit manually.",
        "",
        "| Route | Method | Authentication | Permission | Rate limit | Audit event | Production |",
        "|---|---|---|---|---|---|---|",
    ]
    lines.extend(
        f"| `{path}` | {method} | {authentication} | `{permission}` | {rate} | `{audit}` | {production} |"
        for path, method, authentication, permission, rate, audit, production in rows()
    )
    target = Path("docs/security/endpoint-matrix.md")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
