FROM node:22.17.0-alpine3.21 AS dependencies
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci --omit=dev

FROM node:22.17.0-alpine3.21 AS builder
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend ./
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_APP_ENV=production
ARG NEXT_PUBLIC_AUTH_ENABLED=true
ARG NEXT_PUBLIC_ENABLE_ADMIN_PAGES=true
ARG NEXT_PUBLIC_ENABLE_INGESTION_PAGES=true
ARG NEXT_PUBLIC_ENABLE_EVALUATION_PAGES=true
ARG NEXT_PUBLIC_ENABLE_PROMPT_PAGES=true
ARG NEXT_PUBLIC_DEFAULT_LANGUAGE=en
ARG NEXT_PUBLIC_DEFAULT_TIMEZONE=Africa/Cairo
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV NEXT_PUBLIC_AUTH_ENABLED=$NEXT_PUBLIC_AUTH_ENABLED NEXT_PUBLIC_ENABLE_ADMIN_PAGES=$NEXT_PUBLIC_ENABLE_ADMIN_PAGES NEXT_PUBLIC_ENABLE_INGESTION_PAGES=$NEXT_PUBLIC_ENABLE_INGESTION_PAGES NEXT_PUBLIC_ENABLE_EVALUATION_PAGES=$NEXT_PUBLIC_ENABLE_EVALUATION_PAGES NEXT_PUBLIC_ENABLE_PROMPT_PAGES=$NEXT_PUBLIC_ENABLE_PROMPT_PAGES NEXT_PUBLIC_DEFAULT_LANGUAGE=$NEXT_PUBLIC_DEFAULT_LANGUAGE NEXT_PUBLIC_DEFAULT_TIMEZONE=$NEXT_PUBLIC_DEFAULT_TIMEZONE
RUN npm run build

FROM node:22.17.0-alpine3.21 AS runtime
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=3000 HOSTNAME=0.0.0.0
RUN addgroup -S -g 10001 nodejs && adduser -S -u 10001 -G nodejs nextjs
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
USER 10001:10001
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD node -e "fetch('http://127.0.0.1:3000/api/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"
STOPSIGNAL SIGTERM
CMD ["node", "server.js"]
