"""Stable decision, action, priority, risk, and confidence vocabulary."""

from enum import StrEnum


class DecisionType(StrEnum):
    BIN_ATTENTION_PRIORITY = "BIN_ATTENTION_PRIORITY"
    MISSED_COLLECTION_RESPONSE = "MISSED_COLLECTION_RESPONSE"
    SENSOR_MAINTENANCE_RESPONSE = "SENSOR_MAINTENANCE_RESPONSE"
    TRUCK_PERFORMANCE_RESPONSE = "TRUCK_PERFORMANCE_RESPONSE"
    WORKFORCE_OPERATIONAL_RESPONSE = "WORKFORCE_OPERATIONAL_RESPONSE"
    REGIONAL_OPERATIONAL_RESPONSE = "REGIONAL_OPERATIONAL_RESPONSE"
    GENERAL_OPERATIONAL_PRIORITY = "GENERAL_OPERATIONAL_PRIORITY"
    UNSUPPORTED_PREDICTIVE_DECISION = "UNSUPPORTED_PREDICTIVE_DECISION"
    UNSUPPORTED_AUTONOMOUS_ACTION = "UNSUPPORTED_AUTONOMOUS_ACTION"
    UNSUPPORTED_OPTIMIZATION = "UNSUPPORTED_OPTIMIZATION"


class ActionCategory(StrEnum):
    PRIORITIZE_COLLECTION_REVIEW = "PRIORITIZE_COLLECTION_REVIEW"
    REQUEST_INSPECTION = "REQUEST_INSPECTION"
    REQUEST_BATTERY_REPLACEMENT = "REQUEST_BATTERY_REPLACEMENT"
    VALIDATE_CONNECTIVITY = "VALIDATE_CONNECTIVITY"
    ESCALATE_FOR_MANAGER_REVIEW = "ESCALATE_FOR_MANAGER_REVIEW"
    REVIEW_SERVICE_RECORDS = "REVIEW_SERVICE_RECORDS"
    REVIEW_OPERATIONAL_CAPACITY = "REVIEW_OPERATIONAL_CAPACITY"
    REVIEW_FUEL_RECORDS = "REVIEW_FUEL_RECORDS"
    REVIEW_LOAD_AND_DURATION = "REVIEW_LOAD_AND_DURATION"
    REVIEW_ATTENDANCE_COVERAGE = "REVIEW_ATTENDANCE_COVERAGE"
    REVIEW_WORKLOAD_DISTRIBUTION = "REVIEW_WORKLOAD_DISTRIBUTION"
    REVIEW_OVERTIME = "REVIEW_OVERTIME"
    COMBINED_OPERATIONAL_REVIEW = "COMBINED_OPERATIONAL_REVIEW"
    CONTINUE_MONITORING = "CONTINUE_MONITORING"


class DecisionPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ConfidenceLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class RiskCategory(StrEnum):
    OPERATIONAL = "OPERATIONAL"
    SAFETY = "SAFETY"
    SERVICE_CONTINUITY = "SERVICE_CONTINUITY"
    RESOURCE = "RESOURCE"
    DATA_QUALITY = "DATA_QUALITY"
    POLICY_AUTHORITY = "POLICY_AUTHORITY"
    NO_ACTION = "NO_ACTION"


class RiskSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class RiskLikelihood(StrEnum):
    UNLIKELY = "UNLIKELY"
    POSSIBLE = "POSSIBLE"
    LIKELY = "LIKELY"


class DecisionEvidenceType(StrEnum):
    DATABASE = "database"
    DOCUMENT = "document"
    RULE = "configured_rule"
    MODEL = "model"
