"""Object storage contract."""

from typing import Protocol


class ObjectStorage(Protocol):
    async def put(self, namespace: str, data: bytes, *, sha256: str) -> str: ...
    async def get(self, key: str) -> bytes: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def create_signed_download(self, key: str, *, expires_seconds: int = 300) -> str: ...
